### ISSUE TITLE
Touch support in Desktop Library

### ISSUE THREAD

**Issue by iot40-dp** [Accruent/robotframework-zoomba#153]
Hi,

is there any plan to add touch support in Desktop Library?

Thanks

**Comment by Wolfe1** [comment]
Hey @iot40-dp,

We haven't really taken a look at it since no one had asked yet. Should be possible seeing as [WinAppDriver is showing these endpoints as available](https://github.com/microsoft/WinAppDriver/blob/master/Docs/SupportedAPIs.md):

![image](https://user-images.githubusercontent.com/3010366/98703466-21180200-2341-11eb-8f85-5aadc5612b48.png)

Trying to wrap my head around how these actions are different from the current actions, Im guessing these are tap actions on say a tablet?

**Comment by iot40-dp** [comment]
Yes. I have some applications that run on a tablet on Windows in Kiosk mode. This means, there is no mouse and no keyboard available for the end user. Currently the automated tests use mouse and keyboard but since the enduser cannot it would make sense if the automated tests also does not use mouse and keyboard.

**Comment by Wolfe1** [comment]
Excellent point, will look into this soon.

**Comment by Wolfe1** [comment]
Alright @iot40-dp,

So I have added or enabled support for the following keywords:
- Tap
- Double Tap
- Flick
- Flick From Element
- Scroll
- Scroll From Element
- Drag and Drop by Touch
- Drag and Drop by Touch Offset
- Wait For And Tap
- Wait For And Double Tap
- Wait For And Flick From Element
- Wait For And Scroll From Element

'Long Press' (long click) seemed to already exist but just calling it out now. Keyword doc can be found in the branch for now:
https://github.com/Accruent/robotframework-zoomba/blob/touch_support/docs/DesktopLibraryDocumentation.html

Feel free to test the keywords out from the branch if you like, with the holiday I probably won't get it reviewed, merged, and released until next week.

**Comment by hoangx** [comment]
Looks like https://www.codefactor.io/ is broken ?

**Comment by Wolfe1** [comment]
Yeah @hoangx, I noted it in the pull request but that site is down. Not anything broken on our end

**Comment by Wolfe1** [comment]
Well I spoke too soon, released: https://github.com/Accruent/robotframework-zoomba/releases/tag/2.7.0

**Comment by iot40-dp** [comment]
WOW, that was fast. Thanks a lot. I will start using it soon and come back if there are any issues.
